fix `alias_method_chain' error with rails3+
fix undefined method `alias_method_chain' error with rails3+

with redmine4, there would be error, because alias_method_chain is not available after rails3.

NoMethodError: undefined method `alias_method_chain'

http://railscasts.com/episodes/232-routing-walkthrough-part-2?view=asciicast

"This technique is used often in the Rails 3 source code. Earlier versions of Rails used alias_method_chain to override specific behaviour, but now in Rails 3 we can just use super."